Step 5 - New line breaks and commas should be interchangeable between numbers
preetinadkarni/FirstConsoleApp pull request #1
Opened 2021-09-17 03:41 UTC by preetinadkarni

### Step 5 

New line breaks and commas should be interchangeable between numbers.  

~~~
Add("1,2\n3") > Returns 6
Add("3\n5\n3,9") > Returns 20
~~~

2021-09-22 04:31 UTC, ddarylmae requested changes
Good progress! Just need minor changes on naming the tests

2021-09-22 04:31 UTC, ddarylmae commented on UnitTests/UnitTests.cs
> +        public int GivenInputIsAmountOfNumbersWhenAddThenReturnsSumOfNumbers(string input)
Hmmm, basing it off of your other test description, think a better name for this test would be something like _given separated by commas_

2021-09-22 04:31 UTC, ddarylmae commented on UnitTests/UnitTests.cs
> +        public int GivenInputHasLineBreaksOrCommashenAddThenReturnsSumOfNumbers(string input)
`WhenAdd`?

2021-09-23 04:58 UTC, preetinadkarni commented on UnitTests/UnitTests.cs
> +        public int GivenInputHasLineBreaksOrCommashenAddThenReturnsSumOfNumbers(string input)
good catch!

2021-09-24 02:42 UTC, merged